version: "3.3"

services:
  app:
    container_name: "kantin_dev"
    image: kantin_dev
    build: .
    volumes:
      - .:/kantin_dev
      - node_modules:/app/node_modules
    ports:
      - 5566:5566
    stdin_open: true
    environment:
      PORT: 5566
    command: npm start
  # postgres:
  #   container_name: "postgres_dev"
  #   image: postgres
  #   hostname: postgres
  #   ports:
  #     - "6543:5432"
  #   environment:
  #     POSTGRES_USER: postgresdev
  #     POSTGRES_PASSWORD: dev1234
  #     POSTGRES_DB: kantin_dev
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   restart: unless-stopped
  # pgadmin:
  #   image: dpage/pgadmin4
  #   depends_on:
  #     - postgre
  #   ports:
  #     - "5555:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   restart: unless-stopped
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
volumes:
  node_modules:
  postgres-data:
